### ISSUE TITLE
accounts.us1.gigya.com socialize.us1.gigya.com

### ISSUE THREAD

**Issue by p1r473** [meinhimmel/hosts#1]
Hi, you are blocking the following domains:

accounts.us1.gigya.com
socialize.us1.gigya.com

These domains break logging into iRobot app on Android, and starting iRoomba vacuum from Google Home

**Comment by p1r473** [comment]
Thanks! That was fast, lol

**Comment by dylanarmstrong** [comment]
No problem, thanks for the issue report! Lemme know if you have any more issues
